services:
  nova-image-studio:
    image: ghcr.io/selfancy/nova-image-studio:latest
    container_name: nova-image-studio
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/backend/data
      - ./blacklist.json:/app/backend/blacklist.json
      - ./prompts.json:/app/backend/prompts.json
      - ./.env:/app/backend/.env
    restart: unless-stopped
